x-node-common: &node-common
  image: tiny-p2p-node:dev
  restart: unless-stopped

services:
  node1:
    <<: *node-common
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "./tiny-p2p-node",
        "--nick", "node1",
        "--listen", "/ip4/0.0.0.0/tcp/7001",
        "--topic", "tiny-net"
      ]
    ports:
      - "7001:7001"

  node2:
    <<: *node-common
    depends_on:
      - node1
    command:
      [
        "./tiny-p2p-node",
        "--nick", "node2",
        "--listen", "/ip4/0.0.0.0/tcp/7001",
        "--dial", "/dns4/node1/tcp/7001",
        "--topic", "tiny-net"
      ]

  node3:
    <<: *node-common
    depends_on:
      - node1
    command:
      [
        "./tiny-p2p-node",
        "--nick", "node3",
        "--listen", "/ip4/0.0.0.0/tcp/7001",
        "--dial", "/dns4/node1/tcp/7001",
        "--topic", "tiny-net"
      ]
